<?php
/**
 * XML Sitemap Generator
 * Access as sitemap.xml via rewrite rule or direct request
 */

header('Content-Type: application/xml; charset=utf-8');
echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Main landing pages -->
  <url>
    <loc>https://artbackstage.at/index.php</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/index_en.php</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>

  <!-- Money section -->
  <url>
    <loc>https://artbackstage.at/index_money.php</loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/index_money_en.php</loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/forecast.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/forecast_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/hourly_rate.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/hourly_rate_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/freelance_services_calculator.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/yearly_turnover_calculator.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/yearly_turnover_calculator_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/personalplanung.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/personalplanung_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/honorarium_questionnaire.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/honorarium_questionnaire_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/net_income_carousel.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/net_income_carousel_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/fun_calculator.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/fun_calculator_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/salary_data.php</loc>
    <changefreq>quarterly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/salary_data_en.php</loc>
    <changefreq>quarterly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/bildrecht_tarifliste.php</loc>
    <changefreq>quarterly</changefreq>
    <priority>0.7</priority>
  </url>

  <!-- Law section -->
  <url>
    <loc>https://artbackstage.at/index_law.php</loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/agreement_checklist.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/agreement_checklist_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/curator_viability_carousel.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/curator_viability_carousel_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/gallery_contract_reality_check.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/gallery_contract_reality_check_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>

  <!-- Social section -->
  <url>
    <loc>https://artbackstage.at/index_soziales.php</loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/index_soziales_en.php</loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/onace_story_table.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/onace_story_table_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/gender_report_summary.php</loc>
    <changefreq>quarterly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/gender_report_summary_en.php</loc>
    <changefreq>quarterly</changefreq>
    <priority>0.7</priority>
  </url>

  <!-- FAQ & Info pages -->
  <url>
    <loc>https://artbackstage.at/faq.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/faq_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/sources.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/sources_en.php</loc>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/datenschutz.php</loc>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/datenschutz_en.php</loc>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/impressum.php</loc>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://artbackstage.at/impressum_en.php</loc>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
</urlset>
